//! Fides egress declarations: a `system` fragment to merge into a Fides data map.
//!
//! Field names follow the Fideslang version the vendored taxonomy comes from (3.1.3):
//! `System.egress` is a list of `DataFlow { fides_key, type, data_categories }`, where `type`
//! is `system` for another system. Only categories that are keys of the vendored taxonomy are
//! written; flows whose category is `unknown` are listed in a comment instead, because Fides
//! has no key for "not yet classified".

use std::fmt::Write;

use crate::report::Document;

/// A YAML double-quoted scalar.
fn q(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

pub fn render(doc: &Document) -> String {
    let mut out = String::new();
    let commit = doc
        .subject
        .commit
        .as_deref()
        .unwrap_or("an uncommitted tree");
    let _ = writeln!(
        out,
        "# Fides egress declarations generated by privacy-flow {} from {}.",
        doc.tool.version, commit
    );
    out.push_str("# A fragment to merge into a Fides data map (for example .fides/datamap.yml): it carries\n");
    out.push_str("# egress only. Privacy declarations (data use, data subjects, legal basis) are judgements\n");
    out.push_str("# this tool does not make; add them where you maintain the system.\n");
    let (key, name) = match &doc.system {
        Some(s) => (s.fides_key.clone(), s.name.clone()),
        None => {
            out.push_str("# Set system.fides_key in .privacy-flow.yml to name this system.\n");
            ("this_system".to_string(), None)
        }
    };
    out.push_str("system:\n");
    let _ = writeln!(out, "  - fides_key: {}", q(&key));
    if let Some(n) = name {
        let _ = writeln!(out, "    name: {}", q(&n));
    }
    let keyed: Vec<_> = doc
        .egress
        .iter()
        .filter(|e| e.fides_key.is_some())
        .collect();
    if keyed.is_empty() {
        out.push_str("    egress: []\n");
    } else {
        out.push_str("    egress:\n");
        // One DataFlow per processor key, across sink classes.
        let mut merged: std::collections::BTreeMap<
            String,
            (std::collections::BTreeSet<String>, Vec<String>, bool),
        > = Default::default();
        for e in &keyed {
            let k = e.fides_key.clone().expect("filtered");
            let entry = merged.entry(k).or_default();
            for c in &e.categories {
                if c == crate::classify::UNKNOWN {
                    entry.2 = true;
                } else {
                    entry.0.insert(c.clone());
                }
            }
            let label = format!(
                "{}{}{}",
                e.processor.as_deref().unwrap_or("?"),
                if e.declared { "" } else { " (undeclared)" },
                format_args!(" via {}", e.class.as_str())
            );
            entry.1.push(label);
        }
        for (k, (cats, labels, unknown)) in merged {
            let _ = writeln!(out, "      # {}", labels.join("; "));
            if unknown {
                out.push_str("      # also data of unknown category (request input not narrowed by a type): review\n");
            }
            let _ = writeln!(out, "      - fides_key: {}", q(&k));
            out.push_str("        type: \"system\"\n");
            if !cats.is_empty() {
                out.push_str("        data_categories:\n");
                for c in cats {
                    let _ = writeln!(out, "          - {}", q(&c));
                }
            }
        }
    }
    let unkeyed: Vec<_> = doc
        .egress
        .iter()
        .filter(|e| e.fides_key.is_none())
        .collect();
    if !unkeyed.is_empty() {
        out.push_str(
            "# Egress without a processor key (dynamic hosts, run-time model providers):\n",
        );
        for e in unkeyed {
            let _ = writeln!(
                out,
                "#   {} — {} flow(s), categories: {}",
                e.class.as_str(),
                e.flows.len(),
                e.categories.join(", ")
            );
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::q;

    #[test]
    fn quotes() {
        assert_eq!(q("a\"b\\c"), "\"a\\\"b\\\\c\"");
        assert_eq!(q("x\ny"), "\"x\\ny\"");
    }
}
