//! The review queue: what needs a human (or an agent working for one) to decide.
//!
//! Each item says what would resolve it, and every resolution is recorded somewhere `piiflow`
//! reads as configuration or a disposition, with a citation: `not_personal` or `fields` in
//! `.privacy-flow.yml`, a catalogue entry, or a disposition on the finding. `piiflow` never reads
//! answers back from this file; it is a work list, not an input.

use std::fmt::Write;

use crate::report::{DispositionStatus, Document};

pub fn render(doc: &Document) -> String {
    let mut out = String::new();
    let flows: std::collections::BTreeMap<&str, &crate::report::FlowRec> =
        doc.flows.iter().map(|f| (f.id.as_str(), f)).collect();
    let sources: std::collections::BTreeMap<&str, &crate::report::SourceRec> =
        doc.sources.iter().map(|s| (s.id.as_str(), s)).collect();
    let open = |f: &&crate::report::FindingRec| {
        f.disposition
            .as_ref()
            .is_none_or(|d| d.status == DispositionStatus::Open)
    };

    let _ = writeln!(out, "# privacy-flow review queue\n");
    let _ = writeln!(
        out,
        "Generated by privacy-flow {} from {}. Each item needs a decision. Record it where piiflow reads it, with a citation; editing this file changes nothing.\n",
        doc.tool.version,
        doc.subject
            .commit
            .as_deref()
            .unwrap_or("an uncommitted tree")
    );

    // Names that are only maybe personal, grouped by name.
    let mut by_name: std::collections::BTreeMap<String, Vec<&crate::report::FindingRec>> =
        Default::default();
    for f in doc
        .findings
        .iter()
        .filter(|f| f.rule_id != "PFC01" && f.needs_review)
        .filter(open)
    {
        let name = f
            .flow
            .as_deref()
            .and_then(|id| flows.get(id))
            .and_then(|fl| sources.get(fl.source.as_str()))
            .map(|s| s.name.clone())
            .unwrap_or_default();
        by_name.entry(name).or_default().push(f);
    }
    let _ = writeln!(
        out,
        "## Data that may be personal ({} finding(s))\n",
        by_name.values().map(Vec::len).sum::<usize>()
    );
    if by_name.is_empty() {
        out.push_str("None.\n\n");
    } else {
        out.push_str("Decide per name: if it is personal data, add it under `fields` in `.privacy-flow.yml` with its category; if it is not, add it under `not_personal`. Both need a citation. Request input of category `unknown` is personal until a typed schema narrows it.\n\n");
        for (name, fs) in &by_name {
            let label = if name.is_empty() {
                "(unnamed)"
            } else {
                name.as_str()
            };
            let _ = writeln!(out, "- [ ] `{label}` — {} finding(s)", fs.len());
            for f in fs.iter().take(10) {
                let loc = f
                    .location
                    .as_ref()
                    .map(|l| format!("{}:{}", l.path, l.line))
                    .unwrap_or_default();
                let _ = writeln!(out, "  - {} `{}` at {loc}: {}", f.rule_id, f.id, f.message);
            }
            if fs.len() > 10 {
                let _ = writeln!(
                    out,
                    "  - … and {} more (`piiflow explain <id>` for any of them)",
                    fs.len() - 10
                );
            }
        }
        out.push('\n');
    }

    let gaps: Vec<&crate::report::FindingRec> = doc
        .findings
        .iter()
        .filter(|f| f.rule_id == "PFC01")
        .filter(open)
        .collect();
    let _ = writeln!(out, "## Coverage gaps ({})\n", gaps.len());
    if gaps.is_empty() {
        out.push_str("None: coverage is complete for the scanned scope.\n");
    } else {
        out.push_str("Each is a place the analysis could not see. Resolve it by teaching the catalogue (a sink, propagator or sanitiser in `.privacy-flow.yml`, with a citation), or review it and record a disposition on its finding. See docs/rules/PFC01.md.\n\n");
        let by_gap: std::collections::BTreeMap<&str, &crate::report::GapRec> = doc
            .coverage
            .gaps
            .iter()
            .map(|g| (g.id.as_str(), g))
            .collect();
        for f in gaps {
            let Some(g) = f.gap.as_deref().and_then(|id| by_gap.get(id)) else {
                continue;
            };
            let first = g.locations.first().map(|l| match l.line {
                Some(line) => format!("{}:{line}", l.path),
                None => l.path.clone(),
            });
            let _ = writeln!(
                out,
                "- [ ] `{}` {} — {} ({} location(s){}) — finding `{}`",
                g.kind,
                g.detail,
                first.unwrap_or_default(),
                g.locations.len(),
                if g.sources.is_empty() {
                    String::new()
                } else {
                    format!(", reached by {} source(s)", g.sources.len())
                },
                f.id
            );
        }
    }
    out
}
